### PR TITLE
Fixed Cell templates not loading by using "$templateCache"

### PR DESCRIPTION
**Pull request by travisgoldie**

### CODE REVIEW

**Comment by siosTomBeckenhauer** [comment]
did you see this [comment](https://github.com/angular-ui/ui-grid/pull/601#issuecomment-41093224)? We might be able to fix this by bumping one point release.

**Comment by travisgoldie** [comment]
Last time I looked at using the templateCache with nggrid I remembered seeing that. The reason we can not use that commit directly, is that applies to the main source code. Because our monkey patches are in the build versions we cannot just rebuild it with that fix in it.

That commit is functionally the same as the one provided (just a little shorter)

**Comment by siosTomBeckenhauer** [comment]
Why don't we re-base our monkey patches on top of that commit?

**Comment by travisgoldie** [comment]
I guess we could. I guess if we export the patch from this repo, fork the main ng-grid, apply the commit you mentioned above, then apply the orig monkey patch, build the package, finally publish to this repo.

Does that sound correct?

**Comment by travisgoldie** [comment]
The next question would be what do we gain from doing that extra work?

**Comment by siosTomBeckenhauer** [comment]
I think it could be easier.
1. Fork the repo@ 2.0.7
2. replace all code in repo with ours
3. commit our differences
4. rebase

We get a clearer seperation of our code and theirs.  It makes it easier for us to undo our changes and move in the new ui-grid.

**Comment by siosTomBeckenhauer** [comment]
and if any more importatn fixes for ng-grid come in we can just rebase

**Comment by travisgoldie** [comment]
The original monkey patch is not against one of the source files, only on the build artifact. Therefore we cannot just copy our code over.

**Pull request merged**
